import ImageListing1 from "@/assets/images/listing/1.jpg";
import ImageListing10 from "@/assets/images/listing/10.jpg";
import ImageListing11 from "@/assets/images/listing/11.jpg";
import ImageListing12 from "@/assets/images/listing/12.jpg";
import ImageListing2 from "@/assets/images/listing/2.jpg";
import ImageListing3 from "@/assets/images/listing/3.jpg";
import ImageListing4 from "@/assets/images/listing/4.jpg";
import ImageListing5 from "@/assets/images/listing/5.jpg";
import ImageListing6 from "@/assets/images/listing/6.jpg";
import ImageListing7 from "@/assets/images/listing/7.jpg";
import ImageListing8 from "@/assets/images/listing/8.jpg";
import ImageListing9 from "@/assets/images/listing/9.jpg";


const listingCard = [
  {
    id: 1,
    featured: true,
    image: ImageListing1,
    photosCount: 22,
    videosCount: 3,
    title: "Volvo XC90 - 2023",
    price: 129,
    rating: 4.7,
    reviewsCount: 684,
    mileage: "4789",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["used"],
  },
  {
    id: 2,
    featured: true,
    image: ImageListing2,
    photosCount: 33,
    videosCount: 4,
    title: "Mercedes-Benz S 560 - 2021",
    price: 56,
    rating: 4.7,
    reviewsCount: 565,
    mileage: "6786",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["new"],
  },
  {
    id: 3,
    featured: false,
    image: ImageListing3,
    photosCount: 55,
    videosCount: 3,
    title: "BMW M8 Gran Coupe Base - 2023",
    price: 230,
    rating: 4.7,
    reviewsCount: 323,
    mileage: "7866",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["used"],
  },
  {
    id: 4,
    featured: true,
    image: ImageListing4,
    photosCount: 12,
    videosCount: 3,
    title: "Nıssan Qasqai - Sky Pack",
    price: 478,
    rating: 4.7,
    reviewsCount: 345,
    mileage: "5436",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["new", "used"],
  },
  {
    id: 5,
    featured: false,
    image: ImageListing5,
    photosCount: 22,
    videosCount: 3,
    title: "Audi A8 L 55 - 2021",
    price: 129,
    rating: 4.7,
    reviewsCount: 684,
    mileage: "4789",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["used"],
  },
  {
    id: 6,
    featured: false,
    image: ImageListing6,
    photosCount: 33,
    videosCount: 4,
    title: "Land Rover Range HSE Westminster",
    price: 56,
    rating: 4.7,
    reviewsCount: 565,
    mileage: "6786",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["new", "used"],
  },
  {
    id: 7,
    featured: true,
    image: ImageListing7,
    photosCount: 55,
    videosCount: 3,
    title: "Bentley Bentayga V8 - 2023",
    price: 230,
    rating: 4.7,
    reviewsCount: 323,
    mileage: "7866",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["used", "new"],
  },
  {
    id: 8,
    featured: true,
    image: ImageListing8,
    photosCount: 12,
    videosCount: 3,
    title: "Ferrari 488 Spider Base - 2019",
    price: 478,
    rating: 4.7,
    reviewsCount: 345,
    mileage: "5436",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["new", "used"],
  },
  {
    id: 9,
    featured: false,
    image: ImageListing9,
    photosCount: 22,
    videosCount: 3,
    title: "Audi A8 L 55 - 2021",
    price: 129,
    rating: 4.7,
    reviewsCount: 684,
    mileage: "4789",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["used"],
  },
  {
    id: 10,
    featured: true,
    image: ImageListing10,
    photosCount: 33,
    videosCount: 4,
    title: "Land Rover Range HSE Westminster",
    price: 56,
    rating: 4.7,
    reviewsCount: 565,
    mileage: "6786",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["new", "used"],
  },
  {
    id: 11,
    featured: true,
    image: ImageListing11,
    photosCount: 55,
    videosCount: 3,
    title: "Bentley Bentayga V8 - 2023",
    price: 230,
    rating: 4.7,
    reviewsCount: 323,
    mileage: "7866",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["used", "new"],
  },
  {
    id: 12,
    featured: true,
    image: ImageListing12,
    photosCount: 12,
    videosCount: 3,
    title: "Ferrari 488 Spider Base - 2019",
    price: 478,
    rating: 4.7,
    reviewsCount: 345,
    mileage: "5436",
    fuelType: "Diesel",
    transmission: "Automatic",
    tags: ["new", "used"],
  },
];

export default listingCard;
