import Home from '../components/home';
import Wrapper from '../components/layout/wrapper';

export const metadata = {
  title: 'Home || BliMobilId',
  description: 'Generated by create next app',
};

export default function MainRoot() {
  return (
    <Wrapper>
      <Home />
    </Wrapper>
  );
}
